language: node_js

node_js:
- node
- '8'
cache:
  directories:
  - node_modules
install:
- npm install

script:
- npm run build

addons:
  ssh_known_hosts: 115.159.209.131:28331

before_install:
- openssl aes-256-cbc -K $encrypted_f812e1a00ef1_key -iv $encrypted_f812e1a00ef1_iv -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 115.159.209.131\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- rsync -avz -e 'ssh -p 28331' dist/* root@115.159.209.131:/www/wwwroot/music.io-code.com
- ssh -f root@115.159.209.131 -p 28331 "chown -R www:www /www/wwwroot/music.io-code.com/*"
- echo -e "\033[32m 已同步到网站 \033[0m"

notifications:
  email: false
